language: python
python:
  - 3.7
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - conda install shapely
# command to install dependencies
install:
  - pip install .
# command to run tests
script:
  - pytest